import type { Command } from "commander";

import { action } from "../context.js";
import { AxiError } from "../errors.js";

/**
 * Static shell completion generated from the LIVE command tree at runtime
 * (commander's Help API skips hidden commands), so scripts can never drift
 * from the real surface. No dynamic completion (dseq etc.) by design.
 */

interface Spec {
  name: string;
  description: string;
  options: string[];
  subs: Spec[];
}

/** Keep descriptions shell-safe: first clause, no quotes/colons/backticks. */
function clean(description: string): string {
  const first = description.split(/[.(]/)[0] ?? "";
  return first.replace(/['":`$\\]/g, "").trim().slice(0, 60);
}

function toSpec(cmd: Command): Spec {
  const help = cmd.createHelp();
  return {
    name: cmd.name(),
    description: clean(cmd.description()),
    options: help
      .visibleOptions(cmd)
      .map((o) => o.long)
      .filter((l): l is string => Boolean(l)),
    subs: help.visibleCommands(cmd).map((sub) => toSpec(sub))
  };
}

function rootSpec(command: Command): Spec {
  let root: Command = command;
  while (root.parent) root = root.parent;
  return toSpec(root);
}

const BIN = "console-axi";
const FUNC = "_console_axi";

function bashScript(root: Spec): string {
  const top = [...root.subs.map((s) => s.name), ...root.options].join(" ");
  const cases = root.subs
    .map((sub) => {
      const words =
        sub.subs.length > 0
          ? [...sub.subs.map((s) => s.name), ...new Set(sub.subs.flatMap((s) => s.options))]
          : sub.options;
      return `    ${sub.name}) COMPREPLY=( $(compgen -W "${[...words, ...root.options].join(" ")}" -- "$cur") );;`;
    })
    .join("\n");

  return `# bash completion for ${BIN} (generated by \`${BIN} completion bash\`)
${FUNC}() {
  local cur first
  cur="\${COMP_WORDS[COMP_CWORD]}"
  first="\${COMP_WORDS[1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "${top}" -- "$cur") )
    return
  fi
  case "$first" in
${cases}
    *) COMPREPLY=( $(compgen -W "${root.options.join(" ")}" -- "$cur") );;
  esac
}
complete -F ${FUNC} ${BIN}
`;
}

function zshScript(root: Spec): string {
  const commands = root.subs.map((s) => `    '${s.name}:${s.description}'`).join("\n");
  const cases = root.subs
    .filter((s) => s.subs.length > 0 || s.options.length > 0)
    .map((sub) => {
      const words =
        sub.subs.length > 0
          ? sub.subs.map((s) => `'${s.name}:${s.description}'`)
          : sub.options.map((o) => `'${o}'`);
      return `        ${sub.name}) _values '${sub.name}' ${words.join(" ")} ${root.options.map((o) => `'${o}'`).join(" ")} ;;`;
    })
    .join("\n");

  return `#compdef ${BIN}
# zsh completion for ${BIN} (generated by \`${BIN} completion zsh\`)
${FUNC}() {
  local -a commands
  commands=(
${commands}
  )
  _arguments -C '1: :->cmds' '*:: :->args'
  case $state in
    cmds) _describe 'command' commands ;;
    args)
      case $words[1] in
${cases}
        *) _values 'flags' ${root.options.map((o) => `'${o}'`).join(" ")} ;;
      esac
      ;;
  esac
}
${FUNC} "$@"
`;
}

function fishScript(root: Spec): string {
  const lines: string[] = [`# fish completion for ${BIN} (generated by \`${BIN} completion fish\`)`, `complete -c ${BIN} -f`];
  const subNames = root.subs.map((s) => s.name).join(" ");
  for (const sub of root.subs) {
    lines.push(`complete -c ${BIN} -n "not __fish_seen_subcommand_from ${subNames}" -a ${sub.name} -d '${sub.description}'`);
    if (sub.subs.length > 0) {
      lines.push(
        `complete -c ${BIN} -n "__fish_seen_subcommand_from ${sub.name}" -a "${sub.subs.map((s) => s.name).join(" ")}"`
      );
    }
    for (const option of sub.subs.length > 0 ? [...new Set(sub.subs.flatMap((s) => s.options))] : sub.options) {
      lines.push(`complete -c ${BIN} -n "__fish_seen_subcommand_from ${sub.name}" -l ${option.replace(/^--/, "")}`);
    }
  }
  for (const option of root.options) {
    lines.push(`complete -c ${BIN} -l ${option.replace(/^--/, "")}`);
  }
  return `${lines.join("\n")}\n`;
}

export function completionScript(command: Command, shell: string): string {
  const root = rootSpec(command);
  if (shell === "bash") return bashScript(root);
  if (shell === "zsh") return zshScript(root);
  if (shell === "fish") return fishScript(root);
  throw new AxiError({
    code: "usage",
    message: `Unsupported shell "${shell}". Use bash, zsh, or fish.`,
    help: ["console-axi completion bash", "console-axi completion zsh", "console-axi completion fish"]
  });
}

export function registerCompletion(program: Command): void {
  program
    .command("completion <shell>")
    .description("Print a bash/zsh/fish completion script (raw on stdout, redirect or source it)")
    .action(
      action((shell: string, _opts: unknown, command: Command) => {
        process.stdout.write(completionScript(command, shell.toLowerCase()));
      })
    );
}
